# Generated by Django 2.1.7 on 2019-03-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190318_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
