# Generated by Django 2.1.7 on 2019-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
