# Generated by Django 2.1.7 on 2019-03-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
